### ISSUE TITLE
Support manual key storage

### ISSUE THREAD

**Issue by nakajima** [xmtp/xmtp-react-native#10]
https://github.com/xmtp/xmtp-js#manually-handle-private-key-storage

Note: once the iOS/Android SDKs support the keystore API, this will be deprecated.

**Comment by michaelx11** [comment]
FYI - this is unrelated but old docs might reference this issue number when they really mean: https://github.com/xmtp/xmtp-react-native-old/issues/10 - those links were broken in the renaming shuffle
