### ISSUE TITLE
Android: stopping stream and streaming again fails

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#138]
Android: stopping stream and streaming again fails - GRPC errors Received GOAWAY with ENHANCE_YOUR_CALM

**Comment by jingledongding** [comment]
ERROR in listMessages [Error: Call to function 'XMTP.loadMessages' has been rejected.
→ Caused by: io.grpc.StatusException: UNAVAILABLE: End of stream or IOException] 
I have something error similarly

**Comment by nplasterer** [comment]
I think these issues should be fixed now in the latest release [v1.19.2](https://github.com/xmtp/xmtp-react-native/releases/tag/v1.19.2) feel free to reopen if that is not the case!
