### ISSUE TITLE
Bug: Missing argument for parameter 'idempotencyLevel' in call

### ISSUE THREAD

**Issue by WilliamYWY** [xmtp/xmtp-react-native#153]
### Describe the bug

After installing the package with the steps provided in the repo.
1. install expo (working fine)
2. npm i @xmtp/react-native-sdk
3. Modified ios/Podfile
4. npm pod-install

Getting this error in xcode "Missing argument for parameter 'idempotencyLevel' in call" and cannot build the app
![Screenshot 2023-11-23 at 6 03 35 PM](https://github.com/xmtp/xmtp-react-native/assets/92711171/d9f4da5c-7df1-4057-8cf0-f119138d305f)
![Screenshot 2023-11-23 at 6 04 30 PM](https://github.com/xmtp/xmtp-react-native/assets/92711171/f2289e23-982c-488a-8935-638cf4515a65)

### Expected behavior

Build the app successfully

**Comment by nplasterer** [comment]
We're working on the fix here. https://github.com/xmtp/xmtp-ios/pull/192

**Comment by nplasterer** [comment]
@peterferguson @WilliamYWY Please reopen if this issue still persists on the latest build. But should be fixed now on v1.20.2. 🙏
