### ISSUE TITLE
Example app: Fix replies

### ISSUE THREAD

**Issue by daria-github** [xmtp/xmtp-react-native#161]
### Is your feature request related to a problem?

Replies are no working reflecting properly in the example app. They likely broke with this PR: https://github.com/xmtp/xmtp-react-native/pull/155 

### Describe the solution to the problem

Add back logic so replies visually are shown as attached to the parent message.

Can reference xmtp.chat while building where replies have already been added as well to cross-check this functionality.

Would be good to have an E2E test for this to avoid similar breakages in the future.

### Additional details

May want to pull in this ticket after some of the E2E test boilerplate is in place.

**Comment by alexrisch** [comment]
Fixed in beta branch
