### ISSUE TITLE
Feature request: Make the Library Findable in the React Native Directory

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#168]
### Is your feature request related to a problem?

Most documentation for React Native and Expo point users to https://reactnative.directory/ but xmtp-react-native is not findable there

### Describe the solution to the problem

Make a PR to add the project to the directory

### Describe the uses cases for the feature

Can search and find Xmtp React Native package in the directory

**Comment by Simek** [comment]
Hello @alexrisch, I have added the package to the directory in:
* https://github.com/react-native-community/directory/pull/1102

![Screenshot 2024-01-07 at 23 53 18](https://github.com/xmtp/xmtp-react-native/assets/719641/b6d70fbc-cfc8-43b4-8eab-3fb2f9a28e74)

**Comment by alexrisch** [comment]
Awesome, thank you so much!
