### ISSUE TITLE
Bug: unsubscribeFromMessages cannot unsubscribe from the stream.

### ISSUE THREAD

**Issue by jingledongding** [xmtp/xmtp-react-native#180]
### Describe the bug

When I exit the chat, I am unable to unsubscribe from the message stream using unsubscribeFromMessages

### Expected behavior

 return () => {
      if (conversation) {
        console.log(
          conversation.client.address,
          conversation.topic,
        );
        unsubscribeFromMessages(
          conversation.client.address,
          conversation.topic,
        );
      }
    };

**Comment by kele-leanes** [comment]
hi @jingledongding 
Do you mind showing me how you're doing the subscribing? Are you trying to unsubscribe when the user is logged out? What do you mean by exit the chat?

**Comment by jingledongding** [comment]
`export function useXmtpStream(
  conversation?: Conversation<NativeMessageContent>,
) {

  useEffect(() => {
    const streamMessages = async () => {
      if (!conversation) {
        return;
      }
      conversation.streamMessages(async message => {
        console.log(message);
      });
    };
    streamMessages();
    return () => {
      if (conversation) {
        unsubscribeFromMessages(
          conversation.client.address,
          conversation.topic,
        );
      }
    };
  }, [conversation]);
}`
I'm wondering if it's my code that's wrong. But when I open the chat multiple times, the console.log executes the same number of times as I open the chat window

**Comment by nplasterer** [comment]
Should be fixed in https://github.com/xmtp/xmtp-react-native/pull/187. Feel free to reopen if you are still seeing the issue on the latest version.
