### ISSUE TITLE
Bug: Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.

### ISSUE THREAD

**Issue by WilliamYWY** [xmtp/xmtp-react-native#181]
### Describe the bug

After updating xmtp to the latest version using npm I got this error 

**node_modules/@xmtp/proto/ts/dist/esm/index.js:
Export namespace should be first transformed by `@babel/plugin-transform-export-namespace-from`.**

```
> 1 | export * as messageApi from "./message_api/v1/message_api.pb";
    |        ^^^^^^^^^^^^^^^
  2 | export * as fetcher from "./fetch.pb";
  3 | export * as authn from "./message_api/v1/authn.pb";
  4 | export * as message from "./message_contents/message.pb";
```

### Expected behavior

If someone encounters the same issue, I resolve it by adding the below plugins in babel.config.js
```
{
plugins: ["@babel/plugin-transform-export-namespace-from"]
}
```
Hope this help

**Comment by kele-leanes** [comment]
hi @WilliamYWY can you please provide more information about the issue? how your environment is configured? Have you installed the package in expo or bare RN project?

**Comment by alexrisch** [comment]
Hello!
I just came across this issue, it happens when transitioning from a bare react native project and needing to install.

I will make sure something along the following is added to the ReadMe:
```
Install the required babel plugin:
yarn add @babel/plugin-proposal-export-namespace-from -D

Add '@babel/plugin-proposal-export-namespace-from' to your list of plugins in the babel.config.js file
```
