### ISSUE TITLE
Feature request: Remove Ethers as a dependency

### ISSUE THREAD

**Issue by peterferguson** [xmtp/xmtp-react-native#186]
### Is your feature request related to a problem?

Hey glad to see this package getting so much love over the past few weeks!

Since there are more people working on the package now I was wondering whether there would be capacity to remove `ethers` as a dependency. This is currently to the last library we have that depends explicitly on it & we would really like to remove it from our bundle.

It is really only used [here](https://github.com/xmtp/xmtp-react-native/blob/c51dbbabbb99c044b32e1919758a4eedb460efec/src/lib/Client.ts#L65C9-L73C1) & what it is being used for could easily be broken out into a util in this code base. Or it could even be pushed to the user (probably not ideal).

The benefit here would be allowing the user to decide which type of `Signer` (`viem`, `ethers`, ...) they pass to the `Client` as long as it has a `signMessage` method.

**Comment by nplasterer** [comment]
@peterferguson thanks for reporting! This is something we all really want as well. 

I went through our code to flag the items that we currently use it for
`util.splitSignature`
`signer.signMessage`
`signer.getAddress`

Looks like its really only on creating a client so we should be able to try and prioritize the removal of this. 🙏

**Comment by cameronvoell** [comment]
thanks for taking care of this @kele-leanes ! 

@peterferguson let us know if you have any issues using `viem` or other non `ethers` signer 🙏
