### ISSUE TITLE
Support custom content types with prepareMessage

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#195]
The RN SDK didn’t support custom content types in the conversation.prepareMessage method!
The support for custom content types seems to have introduced a SendOptions parameter to conversation.send  in which we can specify a custom JS content type. Most integrators never use conversation.send directly, instead using conversation.prepareMessage and the sendPreparedMessage method (imported directly from the SDK import { sendPreparedMessage } from "@xmtp/react-native-sdk")

**Comment by alexrisch** [comment]
Fixed in https://github.com/xmtp/xmtp-react-native/pull/198
