### ISSUE TITLE
Feature request: Better Types on Conversation Send Method

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#214]
### Is your feature request related to a problem?

Would like to remove the "any" for the conversation send method

### Describe the solution to the problem

Would likely want it to be a union of potential content that can be sent in some way

### Describe the uses cases for the feature

When sending messages it is helpful for integrators to be able to get expected types

**Comment by peterferguson** [comment]
@alexrisch I had suggested something like this before on another [issue](https://github.com/xmtp/xmtp-react-native/pull/155#discussion_r1408413942)

Might be even easier now that content types are on the client though

**Comment by nplasterer** [comment]
I'm not sure we can do this because of custom content types. But maybe I'm misunderstanding what it is you're looking for?

**Comment by neekolas** [comment]
We added something similar in V11 of `xmtp-js` based on the codecs available. https://github.com/xmtp/xmtp-js/releases/tag/v11.0.0

**Comment by peterferguson** [comment]
> I'm not sure we can do this because of custom content types. But maybe I'm misunderstanding what it is you're looking for?

This linked type would work the same for custom codecs because the user would define their custom codecs on the `Client` and the `send` (or whatever) functions parameter types should just pull from the `Client` generic argument? 

Either way though it looks much the same as what is the referenced by @neekolas above so looking forward to this 🙏

**Comment by alexrisch** [comment]
@peterferguson here's an initial pass at adding types: https://github.com/xmtp/xmtp-react-native/pull/237
I need to verify and probably update a few things with Replies, but should be mostly there otherwise, let me know if you have any thoughts

**Comment by alexrisch** [comment]
Closing out this issue, it will land with the Groups feature
