### ISSUE TITLE
Bug: streamMessages and streamAllMessages stop streaming message after short period of time

### ISSUE THREAD

**Issue by WilliamYWY** [xmtp/xmtp-react-native#306]
### Describe the bug

streamMessages and streamAllMessages work fine when constantly sending messages.
However if idle for about 15 seconds (no message in and out), both streams will stop streaming new messages.

https://github.com/xmtp/xmtp-react-native/assets/92711171/38202605-83da-46db-81f3-d0e0a1a1027f

**Comment by nplasterer** [comment]
Thanks for reporting. We've looking into it. Hope to have a fix by EOD.

**Comment by nplasterer** [comment]
This should be fixed in the latest version 1.29.2. Thanks again for reporting.

**Comment by WilliamYWY** [comment]
Hi, I just updated the package, but I think the problem still remains.
