### ISSUE TITLE
Feature request: Expose find Conversation by Topic

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#317]
### Is your feature request related to a problem?

Would like to not have to request all conversations and search by id on the JS layer

### Describe the solution to the problem

A simple way to access a single conversation can help performance and general usability

### Describe the uses cases for the feature

Deep linking to a conversation by topic
This could also be extended to groups

**Comment by nplasterer** [comment]
This isn't possible with the way V2 is setup but we now have a way to fetch a group by id directly since V3 uses a local database.
