### ISSUE TITLE
Feature request: ability to do batch queries

### ISSUE THREAD

**Issue by nmalzieu** [xmtp/xmtp-react-native#34]
### Is your feature request related to a problem?

Converse syncs all messages for all conversations locally on the phone (so you can access your messages offline)

To do so, for performance reasons (some people have thousands of conversations) we don't call `conversation.messages()` for each conversation, but we use `client.apiClient.batchQuery` and send many topics to get back messages from many conversations at once, then we decode the envelopes ourselves (open issue https://github.com/xmtp/xmtp-js/issues/315 to be able to do it without decoding the envelopes ourselves btw)

This does not seem to be possible in the React Native SDK.
More : calling `conversation.messages()`  seems to return max 100 messages (while the JS SDK returns everything and handles the pagination etc)

### Describe the solution to the problem

Multiple solutions possible:

- add a way to fetch messages for many topics all at once (and the decoding of messages is done by the SDK, like https://github.com/xmtp/xmtp-js/issues/315)
- add a way to do batch queries using the RN SDK: then we also need access to the decoding methods of the SDK directly in RN

Also, `conversation.messages()` should return all messages, not just 100

### Describe the uses cases for the feature

Mostly mobile apps to sync all convos

**Comment by dmccartney** [comment]
Batch listing of messages is now completed for RN on both Android and iOS.
