### ISSUE TITLE
`canGroupMessage` should return array 

### ISSUE THREAD

**Issue by peterferguson** [xmtp/xmtp-react-native#351]
Hey looks like the expected behaviour (from the comment at least) is that the `canGroupMessage` method should return a `Array<boolean>` indicating who can and cannot be messaged as part of the group.

This is not the actual behaviour, the typescript type definitions are correct & the method returns a single `boolean`.

IMO the behaviour in the comment is the preferred behaviour as otherwise the client will have to do a bunch of requests to verify which individuals can & cannot be messaged.

https://github.com/xmtp/xmtp-react-native/blob/0f4739bca0c0bfb8549ce8da89fcbbd7e24692e5/src/lib/Client.ts#L207-L217

**Comment by nplasterer** [comment]
Thanks for reporting! I'll add this to our group chat tracking. Really appreciate you testing GroupChat in Alpha. Feel free to join our group chat checkins from time to time if you'd like to chat with the team directly https://community.xmtp.org/t/group-chat-check-in-agendas-and-recordings/608.

**Comment by nplasterer** [comment]
Rolled this back briefly to investigate a small bug. When remerged can message will now return a hash map of addresses and Booleans.
