### ISSUE TITLE
Feature request: Need additional data for group update content

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#399]
### Is your feature request related to a problem?

When changing the name of a group, would like to have some way to display to other users what has changed

**Comment by neekolas** [comment]
This should be included in the `GroupUpdated` transcript message now. There is a `metadata_field_changes` field that lists the old and new value for each changed field. Would have gone out with the identity release.

**Comment by alexrisch** [comment]
It's probably exposed in Rust, but getting lost somewhere in RN bridge or the native side 
Which is being exposed here: https://github.com/xmtp/xmtp-react-native/blob/beta/android/src/main/java/expo/modules/xmtpreactnativesdk/wrappers/ContentJson.kt#L180
