### ISSUE TITLE
Feature request: Metadata for Group Image

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#413]
### Is your feature request related to a problem?

Would like additional metadata stored/exposed for a group image

**Comment by neekolas** [comment]
@cameronvoell WDYT about adding this in after we add the link field?

We'll probably want to specify the expected aspect ratio and give guidance on resolution to devs, so we don't have a bunch of squished images. Maybe start with a `group_image_square` field and recommendation of 500px?
