### ISSUE TITLE
Feature request: Export InboxId from index

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#424]
### Is your feature request related to a problem?

Export InboxId from index.ts as well

**Comment by peterferguson** [comment]
Hey semi-related to this it would also be nice to expose a static version of the rust `getInboxIdForAddress` method but maybe I should just create a separate issue?

**Comment by alexrisch** [comment]
@peterferguson I made a separate issue for this https://github.com/xmtp/xmtp-react-native/issues/426
