### ISSUE TITLE
Default fallback text for all contentType reference implementations

### ISSUE THREAD

**Issue by yash-luna** [xmtp/xmtp-react-native#43]
Client app agnostic, sender/recipient agnostic default fallback text for content types. Can be along the lines of:

> [<content type>] Cannot display "<content>". This app does not support <content type> yet.

Looping in @jhaaaa for review

**Comment by jhaaaa** [comment]
Thank you for the tag, @yash-luna!

How about:

[] Cannot display "". This app doesn't support it yet.

Here are a few examples of how this template text might play out for different content types:

- [Image] Cannot display "filename.png". This app doesn't support it yet.
- [Reaction] Cannot display "thumbs-up". This app doesn't support it yet.
- [Reply] Cannot display "reply text". This app doesn't support it yet.
- [Payment] Cannot display "1 ETH". This app doesn't support it yet.

I wonder where devs will get the values in quotes?

**Comment by nplasterer** [comment]
This has been fixed in the latest release.
