### ISSUE TITLE
Bug: can't make the RN SDK work in `production` env on iOS

### ISSUE THREAD

**Issue by nmalzieu** [xmtp/xmtp-react-native#51]
### Describe the bug

I can't make the RN SDK work with `production` env. With `dev` env it works on Android & iOS, but with `production` env on iOS I get:

```Error: XMTP Rust Error: status: Unavailable, message: "error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known", details: [], metadata: MetadataMap { headers: {} }```

**Comment by dmccartney** [comment]
This is a bug in the iOS SDK -- the fix is en route: https://github.com/xmtp/xmtp-ios/pull/107
