### ISSUE TITLE
Bug: syncAllGroups takes longer than expected on first run on Android

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#511]
### Describe the bug

Slack Thread: https://xmtp-labs.slack.com/archives/C05GBHEAGPP/p1729097715935989

Seeing the first run of syncAllGroups taking a long amount of time: ~20-40 seconds

This seems to happen mostly for Android
Slack thread has logs from both app and libxmtp

Note this typically happens on the very first load, others will happen a lot quicker

**Comment by nplasterer** [comment]
I've written up a test for this and It seems to be running quickly for me every time. You mind sharing some more details on the environment that is causing this? Possible other streams running? etc... I did see a really large slow down when we got up into 1000 groups that each had 10 new messages but even that was only 13 seconds on Android. We have some ideas for perf improvements for once this list gets larger but that seems unrelated to the issue you are having currently?
