### ISSUE TITLE
Bug: Unable to Import Keys for Clients Generated for the First Time in MessageKit

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-react-native#512]
When generating fresh private keys for a client in MessageKit, key import fails in Converse. However, if the wallet is first generated in Metamask, key import works correctly in Conversr. If the same Metamask-generated wallet is subsequently used in MessageKit, it continues to work in Converse without issues.

Client creation in MessageKit: 
https://github.com/ephemeraHQ/message-kit/blob/main/packages/message-kit/src/lib/client.ts

- Alex noted that works in dev , not in prov.
- Work around. create your wallet in metamask, log it in converse, and then use messagekit

Example: https://xmtp-labs.slack.com/archives/C07DX271K6V/p1729366132276669

**Comment by humanagent** [comment]
Debugged step by step of the client creation in MessageKit and the thing that breaks the import of the privateKey in Converse is this line

https://github.com/ephemeraHQ/message-kit/blob/main/packages/message-kit/src/lib/client.ts

Works in every checkpoint until 

`await client.registerIdentity();`


cc @rygine

**Comment by fabriguespe** [comment]
Related https://github.com/xmtp/xmtp-react-native/issues/512

**Comment by nplasterer** [comment]
Libxmtp calls that happen before error

RN -- create the inboxId for their local database 
`inboxId = getOrCreateInboxId(address)`

RN iOS create --- Succeeds first 
`inboxId = getOrCreateInboxId(account.address)`
`createClient(account.address.lowercased(), inboxId)`
`signatureRequest()`
`addEcdsaSignature()`
`registerIdentity()`

RN iOS buildFromBundle --- then fails to Build
`inboxId = getOrCreateInboxId(address)`
`createClient(account.address.lowercased(), inboxId)` <--- Blows up here


Create![Image](https://github.com/user-attachments/assets/04d3c9f3-6cea-44db-8525-e5c6fa444a40)
