### ISSUE TITLE
Improve V3 Conversation Performance

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#519]
Benchmark and add local mem caching to speed up performance.

**Comment by neekolas** [comment]
What exactly would we be caching? The V2 mem cache is for the conversations, which are already stored in the V3 DB

**Comment by nplasterer** [comment]
So I did a little digging to try and get to the bottom of where the performance issues truly are. This is the side by side comparison of iOS proper and iOS RN. It looks like syncing is just going to be 2x slower than loading from V2 was. Something we would need to improve on the libxmtp side. As for loading it looks like loading in V3 is 3x faster than loading from the mem cache in iOS proper but 3x slower in RN. So something is having trouble serializing across the bridge.

| User  | Action                  | iOS Time (ms)        | RN Time (ms) |
|-------|-------------------------|----------------------|--------------|
| Alix  | loaded 50 v2Convos      | 122.92               | 120          |
| Alix  | 2nd loaded 50 v2Convos  | 9.14                 | 13           |
| Davon | synced 50 Dms           | 307.52               | 240          |
| Davon | loaded 50 Dms           | 3.78                 | 30           |

**Comment by nplasterer** [comment]
So I think the culprit is the `peerInboxId`. I think we need a join table of sorts in libxmtp to make this look up a lot less costly.

**Comment by nplasterer** [comment]
https://github.com/xmtp/libxmtp/issues/1196
