### ISSUE TITLE
Bug: Cannot send message with custom type

### ISSUE THREAD

**Issue by hookie256** [xmtp/xmtp-react-native#563]
### Describe the bug

in React native, I follow example 
[](https://docs.xmtp.org/inboxes/content-types/custom#basic-build-a-custom-content-type-that-multiplies-numbers)
but it return when I call send()
ERROR in send() The operation couldn’t be completed. (XMTPReactNative.ContentJson.Error error 0.)

**Comment by hookie256** [comment]
https://docs.xmtp.org/inboxes/content-types/custom#basic-build-a-custom-content-type-that-multiplies-numbers)

**Comment by nplasterer** [comment]
Added back here: https://github.com/xmtp/xmtp-react-native/pull/559 should be in the next release.

**Comment by nplasterer** [comment]
Released in 3.1.2
