### ISSUE TITLE
Bug: `listBatchMessages` does not handle Date parameters

### ISSUE THREAD

**Issue by nmalzieu** [xmtp/xmtp-react-native#69]
### Describe the bug

it seems the `listBatchMessagesmethod` has an issue with dates :
it expects the before and after to be `Date` objects but when I try to send a date it says `ERROR in listBatchMessages [Error: The 6th argument cannot be cast to type Double?`
also it supposedly returns `DecodedMessage` objects where `sent` is of type `Date` but here I actually have `decodedMessage.sent` = 709725751.7279999 (what does this represent? It’s not a timestamp - this message has been sent recently)

**Comment by daria-github** [comment]
Closed, resolved with https://github.com/xmtp/xmtp-react-native/pull/71

**Comment by nplasterer** [comment]
Release in https://github.com/xmtp/xmtp-react-native/releases/tag/v1.6.1
